# Uncomment the next line to define a global platform for the project
platform :ios, '14.0'

target 'App' do
  use_frameworks!

  # Capacitor plugins
  pod 'Capacitor', :path => '../node_modules/@capacitor/core'
  pod 'CapacitorCamera', :path => '../node_modules/@capacitor/camera'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == 'IONCameraLib' || target.name.include?('ion-ios-camera')
        target.build_configurations.each do |config|
          config.build_settings['SWIFT_STRICT_CONCURRENCY'] = 'minimal'
          config.build_settings['SWIFT_VERSION'] = '5.0'
        end
      end
    end
  end
end